---

version: "3.7"

services:
  app:
    working_dir: /app
    command: ./startup.sh
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - ~/bundle-install:/app/vendor/bundle
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:3000
    links:
      - postgres

  postgres:
    image: postgres:11.2
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
